マッチリクエストacceptの挙動を作った
ut-code/CourseMate pull request #35
Opened 2024-06-16 07:08 UTC by RRRyoma

2024-06-16 08:52 UTC, GaiKOZAKI requested changes
matchHelperの部分でOR使えば二回繰り返さなくても行けると思う

2024-06-16 09:39 UTC, RRRyoma commented
最初orで書いてたんやけどPrismaの型指定に合わないって怒られたんよね‥
> matchHelperの部分でOR使えば二回繰り返さなくても行けると思う

2024-06-16 09:52 UTC, GaiKOZAKI approved these changes

2024-06-16 09:53 UTC, GaiKOZAKI commented
さっき出した別のプルリクでfindFirstだと行けたんだけどなんでだろう？
まあちょっと冗長なだけで処理自体には問題ないと思う

2024-06-18 13:03 UTC, KaichiManabe approved these changes
LGTM！

2024-06-18 13:04 UTC, merged